from dashboard.internet_nl_dashboard.logic.account import save_report_settings, get_report_settings
from dashboard.internet_nl_dashboard.models import Account


def test_urllists(db) -> None:
    account, created = Account.objects.all().get_or_create(name="test")

    settings = {"filters": {"web": {"visible": True}, "web_legacy": {"visible": True}, "mail": {"visible": True},
                            "mail_legacy": {"visible": True}, "internet_nl_web_tls": {"visible": False},
                            "internet_nl_web_dnssec": {"visible": True}, "internet_nl_web_ipv6": {"visible": True},
                            "internet_nl_mail_dashboard_tls": {"visible": True},
                            "internet_nl_mail_dashboard_auth": {"visible": True},
                            "internet_nl_mail_dashboard_dnssec": {"visible": True},
                            "internet_nl_mail_dashboard_ipv6": {"visible": True},
                            "internet_nl_web_https_cert_domain": {"visible": True},
                            "internet_nl_web_https_http_redirect": {"visible": True},
                            "internet_nl_web_https_cert_chain": {"visible": True},
                            "internet_nl_web_https_tls_version": {"visible": True},
                            "internet_nl_web_https_tls_clientreneg": {"visible": True},
                            "internet_nl_web_https_tls_ciphers": {"visible": True},
                            "internet_nl_web_https_http_available": {"visible": True},
                            "internet_nl_web_https_dane_exist": {"visible": True},
                            "internet_nl_web_https_http_compress": {"visible": True},
                            "internet_nl_web_https_http_hsts": {"visible": True},
                            "internet_nl_web_https_tls_secreneg": {"visible": True},
                            "internet_nl_web_https_dane_valid": {"visible": True},
                            "internet_nl_web_https_cert_pubkey": {"visible": True},
                            "internet_nl_web_https_cert_sig": {"visible": True},
                            "internet_nl_web_https_tls_compress": {"visible": True},
                            "internet_nl_web_https_tls_keyexchange": {"visible": True},
                            "internet_nl_web_dnssec_valid": {"visible": True},
                            "internet_nl_web_dnssec_exist": {"visible": True},
                            "internet_nl_web_ipv6_ws_similar": {"visible": True},
                            "internet_nl_web_ipv6_ws_address": {"visible": True},
                            "internet_nl_web_ipv6_ns_reach": {"visible": True},
                            "internet_nl_web_ipv6_ws_reach": {"visible": True},
                            "internet_nl_web_ipv6_ns_address": {"visible": True},
                            "internet_nl_mail_starttls_cert_domain": {"visible": True},
                            "internet_nl_mail_starttls_tls_version": {"visible": True},
                            "internet_nl_mail_starttls_cert_chain": {"visible": True},
                            "internet_nl_mail_starttls_tls_available": {"visible": True},
                            "internet_nl_mail_starttls_tls_clientreneg": {"visible": True},
                            "internet_nl_mail_starttls_tls_ciphers": {"visible": True},
                            "internet_nl_mail_starttls_dane_valid": {"visible": True},
                            "internet_nl_mail_starttls_dane_exist": {"visible": True},
                            "internet_nl_mail_starttls_tls_secreneg": {"visible": True},
                            "internet_nl_mail_starttls_dane_rollover": {"visible": True},
                            "internet_nl_mail_starttls_cert_pubkey": {"visible": True},
                            "internet_nl_mail_starttls_cert_sig": {"visible": True},
                            "internet_nl_mail_starttls_tls_compress": {"visible": True},
                            "internet_nl_mail_starttls_tls_keyexchange": {"visible": True},
                            "internet_nl_mail_auth_dmarc_policy": {"visible": True},
                            "internet_nl_mail_auth_dmarc_exist": {"visible": True},
                            "internet_nl_mail_auth_spf_policy": {"visible": True},
                            "internet_nl_mail_auth_dkim_exist": {"visible": True},
                            "internet_nl_mail_auth_spf_exist": {"visible": True},
                            "internet_nl_mail_dnssec_mailto_exist": {"visible": True},
                            "internet_nl_mail_dnssec_mailto_valid": {"visible": True},
                            "internet_nl_mail_dnssec_mx_valid": {"visible": True},
                            "internet_nl_mail_dnssec_mx_exist": {"visible": True},
                            "internet_nl_mail_ipv6_mx_address": {"visible": True},
                            "internet_nl_mail_ipv6_mx_reach": {"visible": True},
                            "internet_nl_mail_ipv6_ns_reach": {"visible": True},
                            "internet_nl_mail_ipv6_ns_address": {"visible": True},
                            "internet_nl_mail_legacy_dane": {"visible": True},
                            "internet_nl_mail_legacy_tls_available": {"visible": True},
                            "internet_nl_mail_legacy_spf": {"visible": True},
                            "internet_nl_mail_legacy_dkim": {"visible": True},
                            "internet_nl_mail_legacy_dmarc": {"visible": True},
                            "internet_nl_mail_legacy_dnsssec_mailserver_domain": {"visible": True},
                            "internet_nl_mail_legacy_dnssec_email_domain": {"visible": True},
                            "internet_nl_mail_legacy_ipv6_mailserver": {"visible": True},
                            "internet_nl_mail_legacy_ipv6_nameserver": {"visible": True},
                            "internet_nl_web_legacy_dane": {"visible": True},
                            "internet_nl_web_legacy_tls_ncsc_web": {"visible": True},
                            "internet_nl_web_legacy_hsts": {"visible": True},
                            "internet_nl_web_legacy_https_enforced": {"visible": True},
                            "internet_nl_web_legacy_tls_available": {"visible": True},
                            "internet_nl_web_legacy_ipv6_webserver": {"visible": True},
                            "internet_nl_web_legacy_ipv6_nameserver": {"visible": True},
                            "internet_nl_mail_auth_dmarc_policy_only": {"visible": True},
                            "internet_nl_mail_auth_dmarc_ext_destination": {"visible": True},
                            "internet_nl_mail_non_sending_domain": {"visible": True},
                            "internet_nl_mail_server_configured": {"visible": True},
                            "internet_nl_mail_servers_testable": {"visible": True},
                            "internet_nl_mail_starttls_dane_ta": {"visible": True},
                            "internet_nl_web_appsecpriv": {"visible": True},
                            "internet_nl_web_appsecpriv_csp": {"visible": True},
                            "internet_nl_web_appsecpriv_referrer_policy": {"visible": True},
                            "internet_nl_web_appsecpriv_x_content_type_options": {"visible": True},
                            "internet_nl_web_appsecpriv_x_frame_options": {"visible": True},
                            "internet_nl_web_appsecpriv_x_xss_protection": {"visible": True}
                            }
                }
    save_report_settings(account, settings)
    retrieved_settings = get_report_settings(account)

    assert retrieved_settings == settings
