# Generated by Django 3.1.13 on 2021-09-08 12:30

from django.db import migrations

migrate_join_table_data = """
INSERT INTO internet_nl_dashboard_urllist_x_tagged_url (urllist_id,url_id)
  SELECT urllist_id, url_id
  FROM internet_nl_dashboard_urllist_urls
"""


class Migration(migrations.Migration):

    dependencies = [
        ('internet_nl_dashboard', '0004_taggedurlinurllist'),
    ]

    operations = [
        migrations.RunSQL(migrate_join_table_data)
    ]
