# Generated by Django 3.1.13 on 2021-09-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internet_nl_dashboard", "0005_migrate_urlist_to_tagged_urllist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urllist",
            name="urls",
        ),
    ]
