# Generated by Django 2.1.7 on 2019-03-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_nl_dashboard', '0006_uploadlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='enable_logins',
        ),
    ]
