# Generated by Django 3.1.13 on 2021-09-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0060_auto_20200908_1055'),
        ('internet_nl_dashboard', '0006_remove_urllist_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllist',
            name='urls',
            field=models.ManyToManyField(through='internet_nl_dashboard.TaggedUrlInUrllist', to='organizations.Url'),
        ),
    ]
