# Generated by Django 3.1.13 on 2021-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet_nl_dashboard", "0010_subdomaindiscoveryscan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subdomaindiscoveryscan",
            name="state_message",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
