# Generated by Django 2.1.7 on 2019-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet_nl_dashboard", "0010_auto_20190326_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="internet_nl_api_password",
            field=models.BinaryField(blank=True, help_text="New values will automatically be encrypted.", null=True),
        ),
    ]
