# Generated by Django 4.2.13 on 2024-06-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internet_nl_dashboard", "0013_auto_20230302_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadlog",
            name="percentage",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="The percentage of domains added in the upload.", null=True
            ),
        ),
    ]
