# Generated by Django 4.2.13 on 2024-11-12 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("internet_nl_dashboard", "0014_uploadlog_percentage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="urllistreport",
            new_name="internet_nl_at_when_f55fb9_idx",
            old_fields=("at_when", "id"),
        ),
    ]
