# Generated by Django 5.2.2 on 2025-07-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet_nl_dashboard", "0015_rename_urllistreport_at_when_id_internet_nl_at_when_f55fb9_idx"),
        # references 0002_internetnlscaninspection, which does not exist in scanners_internet_nl_web
        # this is an old proxymodel.
        # ("scanners_internet_nl_web", "0002_internetnlscaninspection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountinternetnlscan",
            name="scan",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="scanners_internet_nl_web.internetnlv2scan"
            ),
        ),
    ]
