# Generated by Django 5.2.2 on 2025-07-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internet_nl_dashboard", "0015_rename_urllistreport_at_when_id_internet_nl_at_when_f55fb9_idx"),
    ]

    operations = []
