# Generated by Django 5.2.2 on 2025-11-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("internet_nl_dashboard", "0017_alter_accountinternetnlscan_scan_fk")]

    operations = [
        migrations.AlterField(
            model_name="accountinternetnlscan",
            name="scan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scanners_internet_nl_web.internetnlv2scan",
            ),
        ),
        migrations.AlterField(
            model_name="uploadlog",
            name="message",
            field=models.CharField(
                blank=True,
                help_text="This message gives more specific information about what happened. For example, it might be the case that a file has been rejected because it had the wrong filetype etc.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
