# Generated by Django 2.2 on 2019-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet_nl_dashboard", "0017_urllist_scan_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urllist",
            name="scan_type",
            field=models.CharField(choices=[("web", "web"), ("mail", "mail")], default="web", max_length=4),
        ),
    ]
