# Generated by Django 2.2 on 2019-04-03 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_nl_dashboard', '0018_auto_20190402_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllistreport',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
