# Generated by Django 2.2 on 2019-04-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_nl_dashboard', '0019_urllistreport_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urllistreport',
            options={'get_latest_by': 'at_when'},
        ),
        migrations.RenameField(
            model_name='urllistreport',
            old_name='when',
            new_name='at_when',
        ),
        migrations.AlterIndexTogether(
            name='urllistreport',
            index_together={('at_when', 'id')},
        ),
    ]
