# Generated by Django 2.2.1 on 2019-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_nl_dashboard', '0033_auto_20190604_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='internet_nl_api_password',
            field=models.TextField(blank=True, help_text='New values will automatically be encrypted.', null=True),
        ),
    ]
