# Generated by Django 2.2.6 on 2019-11-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet_nl_dashboard", "0037_auto_20191121_1408"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountinternetnlscan",
            name="state_changed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
