# Generated by Django 2.2.10 on 2020-05-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_nl_dashboard', '0040_auto_20200508_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinternetnlscan',
            name='report',
            field=models.ForeignKey(blank=True, help_text='After a scan has finished, a report is created. This points to that report so no guessing is needed to figure out what report belongs to what scan.',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='internet_nl_dashboard.UrlListReport'),
        ),
    ]
