# Generated by Django 2.2.10 on 2020-05-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet_nl_dashboard", "0041_auto_20200513_1351"),
    ]

    operations = [
        migrations.AddField(
            model_name="urllistreport",
            name="endpoint_error_in_test",
            field=models.IntegerField(default=0, help_text="Amount of errors in tests performed on this endpoint."),
        ),
        migrations.AddField(
            model_name="urllistreport",
            name="error_in_test",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="urllistreport",
            name="url_error_in_test",
            field=models.IntegerField(default=0, help_text="Amount of errors in tests on this url."),
        ),
    ]
