# Generated by Django 3.1.1 on 2020-10-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_nl_dashboard', '0044_dashboarduser_mail_after_mail_unsubscribe_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='mail_after_mail_unsubscribe_code',
            field=models.CharField(
                blank=True, default='', help_text='This is autofilled when sending an e-mail. The user can use this code to set mail_send_mail_after_scan_finished to false without logging in.', max_length=255),
        ),
    ]
